In [16]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)  

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print("Datatype of the object",type(arr))

Datatype of the object <class 'numpy.ndarray'>


In [5]:
print("Datatype of the elements in the array",arr.dtype)

Datatype of the elements in the array int32


In [9]:
print("Dimention of the array is",arr.ndim)

Dimention of the array 2


In [10]:
print("Shape of the object is",arr.shape)


Shape of the object is (3, 3)


In [11]:
print("Size of the array or number of elements",arr.size)

Size of the array or number of elements 9


In [13]:
N = 5
ar = [0]*N  #or can be used [0 for i in range(N)]
print(ar)

[0, 0, 0, 0, 0]


In [17]:
ar = np.array(47) #0 D array
print(ar)

47


In [18]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a)  #3D array
type(a)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


numpy.ndarray

In [24]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)  

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
print(arr[1:3])

[[4 5 6]
 [7 8 9]]


In [28]:
print(arr[1:2,0:3])

[[4 5 6]]


In [29]:
print(arr[ :2])

[[1 2 3]
 [4 5 6]]


In [30]:
print(arr[0:3, 0:2])

[[1 2]
 [4 5]
 [7 8]]
